In [1]:
from DMC_class import *
import numpy as np
from sklearn import datasets

import warnings
warnings.filterwarnings("ignore")

In [2]:
K = 2
L = np.ones((K,K)) - np.eye(K)

In [3]:
np.random.seed(10)
X_train, y_train = datasets.make_blobs(n_samples=[125 * 5, 70 * 3], n_features=2, centers=[(9.5, 10), (9.7, 9.4)],
                                       cluster_std=[[0.6, 0.6], [0.35, 0.3]], shuffle=True, random_state=None)

# X_train = pd.DataFrame(X_train, columns=['X1', 'X2'])
# y_train = pd.DataFrame(y_train+1, columns=['y'])


In [9]:
DMC_model = DMC(T=15,option_info=True,discretization="kmeans")
DMC_model.fit(X_train,y_train)
y_pred = DMC_model.predict(X_train)
compute_conditional_risk(y_train, y_pred, K, L)

(array([0.2352    , 0.15714286]),
 array([[0.7648    , 0.2352    ],
        [0.15714286, 0.84285714]]))

In [5]:
DMC_model = DMC(T=15, m=1.5, discretization="cmeans")
DMC_model.fit(X_train,y_train)
y_pred = DMC_model.predict(X_train)
compute_conditional_risk(y_train, y_pred, K, L)

(array([0.1808    , 0.25238095]),
 array([[0.8192    , 0.1808    ],
        [0.25238095, 0.74761905]]))

In [7]:
DMC_model = DMC(T=15, discretization="GM")
DMC_model.fit(X_train,y_train)
y_pred = DMC_model.predict(X_train)
compute_conditional_risk(y_train, y_pred, K, L)

(array([0.2064    , 0.19047619]),
 array([[0.7936    , 0.2064    ],
        [0.19047619, 0.80952381]]))