In [1]:
from DMC_class import *
import numpy as np
from sklearn import datasets
from sklearn.model_selection import GridSearchCV

import warnings
warnings.filterwarnings("ignore")

In [2]:
K = 2
L = np.ones((K,K)) - np.eye(K)

In [3]:
np.random.seed(10)
X_train, y_train = datasets.make_blobs(n_samples=[125 * 5, 70 * 3], n_features=2, centers=[(9.5, 10), (9.7, 9.4)],
                                       cluster_std=[[0.6, 0.6], [0.35, 0.3]], shuffle=True, random_state=None)


y_train_str = np.where(y_train == 0, 'class0', 'class1')
# y_train = y_train + 10
# X_train = pd.DataFrame(X_train, columns=['X1', 'X2'])
# y_train = pd.DataFrame(y_train+1, columns=['y'])

In [4]:
DMC_model = DMC(T='auto', option_info=True)
DMC_model.fit(X_train, y_train_str)

Caculate T_optimal... Finish
Caculate pHat... Finish
Caculate piStar... Finish
Model fit compiled


In [5]:
DMC_model.T

(array([0.2176    , 0.17619048]),
 array([[0.7824    , 0.2176    ],
        [0.17619048, 0.82380952]]))

In [6]:
y_pred = DMC_model.predict(X_train)
compute_conditional_risk(y_train_str, y_pred, K, L)

array([[0.08474577, 0.91525423],
       [0.60126585, 0.39873415],
       [0.        , 1.        ],
       ...,
       [0.6896552 , 0.3103448 ],
       [0.50000003, 0.49999997],
       [0.09569379, 0.90430621]])

In [6]:
y_pred = DMC_model.predict(X_train, pi=DMC_model.piStar)
compute_conditional_risk(y_train, y_pred, K, L)

In [ ]:
param_grid = {
    'T' : np.linspace(10, 100, 10, dtype=int)
}
grid_search = GridSearchCV(estimator=DMC_model, param_grid=param_grid, cv=2)
grid_search.fit(X_train, y_train, T_start=10, T_end=100, T_step=3)
grid_search.best_params_, grid_search.best_score_

In [ ]:
y_pred = grid_search.best_estimator_.predict(X_train, pi=grid_search.best_estimator_.piStar)
compute_conditional_risk(y_train, y_pred, 2, L)

In [ ]:
y_pred = grid_search.best_estimator_.predict(X_train)
compute_conditional_risk(y_train, y_pred, 2, L)

In [ ]:
DMC_model_optimal = grid_search.best_estimator_
DMC_model_optimal.predict_prob(X_train)

In [ ]:
DMC_model_2 = DMC(T=90)
DMC_model_2.fit(X_train,y_train)
y_pred = DMC_model_2.predict(X_train)
compute_conditional_risk(y_train,y_pred,2,L)